### ISSUE TITLE
Spacing around code blocks is awkward

### ISSUE THREAD

**Issue by pmatulis** [vanilla-framework/vanilla-docs-theme#25]
I find that the spacing around code blocks can be improved.

The below example (taken from a MAAS page [1]) displays code blocks in different contexts. I feel that there should be extra spacing **inserted** after a code block and extra spacing **removed** before a code block.

![vanilla-spacing](https://cloud.githubusercontent.com/assets/6303808/23089995/2581c2ac-f561-11e6-9e57-bb3095fdd874.png)

[1]: https://docs.ubuntu.com/maas/devel/en/intel-rsd

**Comment by yaili** [comment]
This is issue is related to https://github.com/vanilla-framework/vanilla-framework/issues/732

**Comment by anthonydillon** [comment]
@barrymcgee do you think this issue may be resolved with your spacing branch? https://github.com/vanilla-framework/vanilla-docs-theme/issues/25

**Comment by barrymcgee** [comment]
Should be fixed by: https://github.com/vanilla-framework/vanilla-framework/pull/955

**Comment by anthonydillon** [comment]
Could you add Fixes: in the PR above to mix the cards in waffle?

**Comment by barrymcgee** [comment]
Closing this issue as conversation has now moved to #960

**Comment by pmatulis** [comment]
For the record. This issue remains. See [this page](https://docs.maas.io/devel/en/manage-cli-comp-hw#register-a-pod).
